// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/marlonmp/go-basic-library/ent/bookloan"
	"github.com/marlonmp/go-basic-library/ent/predicate"
)

// BookLoanDelete is the builder for deleting a BookLoan entity.
type BookLoanDelete struct {
	config
	hooks    []Hook
	mutation *BookLoanMutation
}

// Where appends a list predicates to the BookLoanDelete builder.
func (bld *BookLoanDelete) Where(ps ...predicate.BookLoan) *BookLoanDelete {
	bld.mutation.Where(ps...)
	return bld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (bld *BookLoanDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(bld.hooks) == 0 {
		affected, err = bld.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BookLoanMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bld.mutation = mutation
			affected, err = bld.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(bld.hooks) - 1; i >= 0; i-- {
			if bld.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = bld.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bld.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (bld *BookLoanDelete) ExecX(ctx context.Context) int {
	n, err := bld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (bld *BookLoanDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: bookloan.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: bookloan.FieldID,
			},
		},
	}
	if ps := bld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, bld.driver, _spec)
}

// BookLoanDeleteOne is the builder for deleting a single BookLoan entity.
type BookLoanDeleteOne struct {
	bld *BookLoanDelete
}

// Exec executes the deletion query.
func (bldo *BookLoanDeleteOne) Exec(ctx context.Context) error {
	n, err := bldo.bld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{bookloan.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (bldo *BookLoanDeleteOne) ExecX(ctx context.Context) {
	bldo.bld.ExecX(ctx)
}
