// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/marlonmp/go-basic-library/ent/book"
	"github.com/marlonmp/go-basic-library/ent/bookloan"
	"github.com/marlonmp/go-basic-library/ent/schema"
	"github.com/marlonmp/go-basic-library/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bookMixin := schema.Book{}.Mixin()
	bookMixinFields0 := bookMixin[0].Fields()
	_ = bookMixinFields0
	bookFields := schema.Book{}.Fields()
	_ = bookFields
	// bookDescCreateAt is the schema descriptor for create_at field.
	bookDescCreateAt := bookMixinFields0[1].Descriptor()
	// book.DefaultCreateAt holds the default value on creation for the create_at field.
	book.DefaultCreateAt = bookDescCreateAt.Default.(func() time.Time)
	// bookDescUpdatedAt is the schema descriptor for updated_at field.
	bookDescUpdatedAt := bookMixinFields0[2].Descriptor()
	// book.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	book.DefaultUpdatedAt = bookDescUpdatedAt.Default.(func() time.Time)
	// book.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	book.UpdateDefaultUpdatedAt = bookDescUpdatedAt.UpdateDefault.(func() time.Time)
	// bookDescID is the schema descriptor for id field.
	bookDescID := bookMixinFields0[0].Descriptor()
	// book.DefaultID holds the default value on creation for the id field.
	book.DefaultID = bookDescID.Default.(func() uuid.UUID)
	bookloanMixin := schema.BookLoan{}.Mixin()
	bookloanMixinFields0 := bookloanMixin[0].Fields()
	_ = bookloanMixinFields0
	bookloanFields := schema.BookLoan{}.Fields()
	_ = bookloanFields
	// bookloanDescCreateAt is the schema descriptor for create_at field.
	bookloanDescCreateAt := bookloanMixinFields0[1].Descriptor()
	// bookloan.DefaultCreateAt holds the default value on creation for the create_at field.
	bookloan.DefaultCreateAt = bookloanDescCreateAt.Default.(func() time.Time)
	// bookloanDescUpdatedAt is the schema descriptor for updated_at field.
	bookloanDescUpdatedAt := bookloanMixinFields0[2].Descriptor()
	// bookloan.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	bookloan.DefaultUpdatedAt = bookloanDescUpdatedAt.Default.(func() time.Time)
	// bookloan.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	bookloan.UpdateDefaultUpdatedAt = bookloanDescUpdatedAt.UpdateDefault.(func() time.Time)
	// bookloanDescLoanDate is the schema descriptor for loan_date field.
	bookloanDescLoanDate := bookloanFields[0].Descriptor()
	// bookloan.DefaultLoanDate holds the default value on creation for the loan_date field.
	bookloan.DefaultLoanDate = bookloanDescLoanDate.Default.(func() time.Time)
	// bookloanDescDeliveryDate is the schema descriptor for delivery_date field.
	bookloanDescDeliveryDate := bookloanFields[1].Descriptor()
	// bookloan.DefaultDeliveryDate holds the default value on creation for the delivery_date field.
	bookloan.DefaultDeliveryDate = bookloanDescDeliveryDate.Default.(func() time.Time)
	// bookloan.UpdateDefaultDeliveryDate holds the default value on update for the delivery_date field.
	bookloan.UpdateDefaultDeliveryDate = bookloanDescDeliveryDate.UpdateDefault.(func() time.Time)
	// bookloanDescID is the schema descriptor for id field.
	bookloanDescID := bookloanMixinFields0[0].Descriptor()
	// bookloan.DefaultID holds the default value on creation for the id field.
	bookloan.DefaultID = bookloanDescID.Default.(func() uuid.UUID)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreateAt is the schema descriptor for create_at field.
	userDescCreateAt := userMixinFields0[1].Descriptor()
	// user.DefaultCreateAt holds the default value on creation for the create_at field.
	user.DefaultCreateAt = userDescCreateAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[2].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userMixinFields0[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
