// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Book is the predicate function for book builders.
type Book func(*sql.Selector)

// BookLoan is the predicate function for bookloan builders.
type BookLoan func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
